name: Releases

on: 
  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Tag
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: ncipollo/release-action@v1
      with:
       generateReleaseNotes: true
       commit: master
       tag: master
