name: Releases

on: 
  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      id:  create_tag
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: ncipollo/release-action@v1
      with:
       generateReleaseNotes: true
       tag: ${{ steps.create_tag.outputs.new_tag }}